name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} - Build native deps
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Linux deps
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            libx11-dev libxext-dev libxrandr-dev libxrender-dev \
            libxfixes-dev libxcursor-dev libxi-dev libxinerama-dev \
            libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libgbm-dev \
            libudev-dev libpulse-dev libpipewire-0.3-dev \
            libwayland-dev wayland-protocols libxkbcommon-dev \
            libasound2-dev libdbus-1-dev libibus-1.0-dev

      - name: macOS deps
        if: startsWith(matrix.os, 'macos')
        shell: bash
        run: |
          brew update
          brew install cmake ninja pkg-config || true

      - name: Windows deps
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y ninja

      - name: Restore .NET tools
        shell: bash
        run: dotnet tool restore

      - name: Cake run
        run: |
          dotnet --info
          dotnet run